matrix:
  include:
    - language: python
      python: 3.8
      cache: pip

      install:
        - pip install -r collector/requirements.txt
        - pip install -r server/requirements.txt
        - pip install -r requirements.txt

      script:
        - pylint --rcfile=.pylintrc ./collector/ --init-hook='sys.path.extend(["./collector/"])'
        - pylint --rcfile=.pylintrc ./server/ --init-hook='sys.path.extend(["./server/"])'

    - language: node_js
      node_js: 14.3
      cache: yarn
      before_install:
        - cd ui
      install:
        - yarn add travis-ci-cloudfront-invalidation
        - yarn install
      script:
        - yarn lint
        - yarn build
      deploy:
        provider: s3
        region: $AWS_REGION
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: $AWS_BUCKET_NAME
        local_dir: ./dist
        skip_cleanup: true
        on:
          branch: develop
      after_deploy:
        - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_DISTRIBUTION_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -o 'develop'

branches:
  only:
  - master
  - develop
