version: '3.7'

services:
  # Set password
  mongodb:
    container_name: jammed_mongodb
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017
    restart: always

  redis:
    image: redis:5
    container_name: jammed_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT:-6379}
    env_file:
      - .env
    restart: always

  collector:
    container_name: jammed_collector
    build: ./collector
    command: python run.py worker -l info
    stdin_open: true
    tty: true
    volumes:
      - /var/log/jammed/collector.log:/var/log/collector.log
      - ./collector:/collector
    depends_on:
      - mongodb
      - redis
    environment:
      - COLUMNS=80
    env_file:
      - .env
    restart: always

  collector_beat:
    container_name: jammed_collector_beat
    build: ./collector
    command: python run.py beat -l info
    stdin_open: true
    tty: true
    volumes:
      - /var/log/jammed/collector.log:/var/log/collector.log
      - ./collector:/collector
    depends_on:
      - redis
      - collector
    environment:
      - COLUMNS=80
    env_file:
      - .env
    restart: always

  server:
    container_name: jammed_server
    build: ./server
    env_file:
      - .env
    command: python run.py
    stdin_open: true
    tty: true
    volumes:
      - /var/log/jammed/server.log:/var/log/server.log
      - ./server:/server
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    restart: always

volumes:
  mongo-data:
