version: '3.7'

services:
  mongodb:
    container_name: jammed_mongodb
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  collector:
    container_name: jammed_collector
    build: ./jammed
    command: bash -c "cron && python manage.py collect -f 300"
    volumes:
      - collected-data:/var/collected
      - /var/log/jammed/collector.log:/var/log/jammed.log
      - .:/jammed
    depends_on:
      - mongodb

  api:
    container_name: jammed_api
    build: ./jammed
    command: python manage.py runserver -d
    volumes:
      - /var/log/jammed/api.log:/var/log/jammed.log
      - .:/jammed
    ports:
      - 5000:5000

  ui:
    container_name: jammed_ui
    build: ./jammed_ui
    command: npm start
    volumes:
      - .:/jammed
      - node-modules:/jammed/jammed_ui/node_modules
    ports:
      - 3000:3000

volumes:
  node-modules:
  mongo-data:
  collected-data:
