version: '3.7'

services:
  # Set password
  mongodb:
    container_name: jammed_mongodb
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017
    restart: always

  collector:
    container_name: jammed_collector
    build: ./collector
    env_file:
      - .env
    command: bash -c "printenv >> /etc/environment && cron && python run.py -f 300"
    stdin_open: true
    tty: true
    volumes:
      - /var/log/jammed/collector.log:/var/log/collector.log
      - ./collector:/collector
    depends_on:
      - mongodb
    restart: always

  server:
    container_name: jammed_server
    build: ./server
    env_file:
      - .env
    command: python run.py
    stdin_open: true
    tty: true
    volumes:
      - /var/log/jammed/server.log:/var/log/server.log
      - ./server:/server
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    restart: always

volumes:
  mongo-data:
